name: Build
on:
  push:
    branches:
      - master
      - develop
jobs:
  build:
    # Run on all label events (won't be duplicated) or all push events or on PR syncs not from the same repo
    if: github.repository_owner == 'OneLiteFeatherNET'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          cache: gradle
          java-version: 21
      - name: Publish to Jar
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
          ./gradlew publish
        env:
          ELDO_USERNAME: "${{ secrets.ELDO_USERNAME }}"
          ELDO_PASSWORD: "${{ secrets.ELDO_PASSWORD }}"